server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shell?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  jpa:
    database: mysql
    show-sql: true
    database-platform: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
      